source 'https://rubygems.org'

gem 'rails', '~> 4.1.4'
gem 'uglifier', '>= 1.3.0'
gem 'sqlite3'
gem 'turbolinks'
gem 'jquery-rails'
gem 'underscore-rails'
gem 'annotate'

# Gems used when running tests.
group :test do
  gem 'rspec-rails', '~> 2.0'
  gem 'capybara'
  gem 'rake'
  gem 'email_spec'
end

